# Completing Random Forest Analysis
Assumption that appropriate separation and PCA has been completed.

## SETUP

In [57]:
import subprocess, sys, os, importlib, re
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import rf_functions 
importlib.reload(rf_functions)

parent_dir=os.path.dirname(os.getcwd())

doscar_files_dir=os.path.join(parent_dir, 'DOSCAR_files')

print(f"The base directory containing all the DOSCAR files is {doscar_files_dir}")

The base directory containing all the DOSCAR files is c:\Users\jespe\Desktop\[THESIS] Code\-ESPEJO-THESIS-DOS-ML-Model-\DOSCAR_files

### STEP 0 : LOAD THE ADSORPTION ENERGY DATA

In [58]:
adsorption_energy_df = pd.read_excel('Adsorption_energies_additives.xlsx')

adsorption_energy_df

                                    System  Ads.
0                1,1,1,2-Tetrachloroethane -0.40
1        1,1,1,3,3,3-Hexafluoro-2-propanol -0.52
2                    1,1,1-Trichloroethane -0.49
3               1,1,1-Trifluoro-2-propanol -0.67
4    1,1,2-trichloro-1,2,2-trifluoroethane -0.45
..                                     ...   ...
285                        Tetramethylurea -1.01
286                              Threonine -0.69
287                        Triethanolamine -0.60
288                               Vanillin -0.53
289                                Xylitol -0.94

[290 rows x 2 columns]

In [59]:
# Initialize an empty list to store the results
results = []

files = ['transformed_data_[-5,5]_var0.80.txt', 
         'transformed_data_[-5,5]_var0.90.txt',
         'transformed_data_[-10,10]_var0.80.txt',
         'transformed_data_[-10,10]_var0.90.txt'
         ]

for filename in files:
    # Load and process the data
    pca_data = rf_functions.load_pca_transformed_data(filename)
    merged_data = rf_functions.adsorption_energy_for_dataset(pca_data, adsorption_energy_df)

    # Perform Random Forest and get mse and r2
    mse, r2 = rf_functions.perform_random_forest(merged_data)

    # Extract the energy range and cumulative variance ratio from the filename
    energy_range = re.search(r'\[(-?\d+,-?\d+)\]', filename).group(1)
    cum_variance = re.search(r'var(\d+\.\d+)', filename).group(1)

    # Append the results to the list as a dictionary
    results.append({
        'filename': filename,
        'energy_range': energy_range,
        'cumulative_variance_ratio': cum_variance,
        'mse': mse,
        'r2': r2
    })

# Convert the results list into a DataFrame
results_df = pd.DataFrame(results)

results_df

,filename,energy_range,cumulative_variance_ratio,mse,r2
0,"transformed_data_[-5,5]_var0.80.txt","-5,5",0.80,0.066489,-0.762539
1,"transformed_data_[-5,5]_var0.90.txt","-5,5",0.90,0.073547,-0.949660
2,"transformed_data_[-10,10]_var0.80.txt","-10,10",0.80,0.045613,-0.209142
3,"transformed_data_[-10,10]_var0.90.txt","-10,10",0.90,0.050884,-0.348890